### ISSUE TITLE
When comparing corev1.Deployment, resource limits & requests are semantically equal, but reported as not equal

### ISSUE THREAD

**Issue by jsenko** [RHsyseng/operator-utils#109]
Affected version: v1.4.7 (I haven't tested the latest, but it seems to be affected.)

When the library is comparing two Deployments in the `equalDeployment(deployed client.Object, requested client.Object) bool` function, two Deployments may be reported as not-equal even if they are semantically equal. This is caused by the use of `reflect.DeepEqual`, which recursively compares nested fields, but fails in a more complex situations. I encountered this bug when having `corev1.ResourceList` in a Deployment, more specifically the `resource.Quantity` struct. 

Here is an example:
```
// This quantity represents "1"
q1 := Quantity {
		// i is the quantity in int64 scaled form, if d.Dec == nil
		i: int64Amount {
			value: &inf.Dec {
				unscaled: big.NewInt(1),
				scale: 0,
			},
		},
		// ignoring other fields
	}
// This quantity also represents "1", but with a different scale (representing the position of the decimal point)
q2 := Quantity {
		// i is the quantity in int64 scaled form, if d.Dec == nil
		i: int64Amount {
			value: &inf.Dec {
				unscaled: big.NewInt(1000),
				scale: 3,
			},
		},
		// ignoring other fields
	}
// This returns false, because it falls back on reflect.DeepEqual
compare.Equals(q1, q2) 
// The Equal function on the Quantity struct correctly returns true
q1.Equal(q2)
```

You can see my workaround for another project here https://github.com/Apicurio/apicurio-operators/pull/68/files#diff-1327b894956778898973053a0942b15a2c9d2cd5f7635130e06dea8524b7b7b1R262 but it should be fixed in the library. I think a proper solution would be to avoid using `reflect.DeepEqual` at all, and use something else. I found other people encountering this issue e.g. https://github.com/kubernetes/apimachinery/issues/75 .

**Comment by jsenko** [comment]
This also worked https://github.com/go-test/deep .

**Comment by ruromero** [comment]
I like the go-test/deep library, thanks for reporting it
