### ISSUE TITLE
Secret comparison issue

### ISSUE THREAD

**Issue by xieshenzh** [RHsyseng/operator-utils#29]
According to Kubernetes [documentation](https://v1-14.docs.kubernetes.io/docs/concepts/configuration/secret/), `stringData` will not be retrieved for `Secret` .

> stringData is a write-only convenience field. It is never output when retrieving Secrets.

So `stringData` should be converted to `data` when comparing  the requested `secret` with the deployed `secret`.

https://github.com/RHsyseng/operator-utils/blob/1b39f571c982ab9b21969a1279bec9f3ceccf1d1/pkg/resource/compare/defaults.go#L478

**Comment by bmozaffa** [comment]
Thanks, @xiezhang7 , can you open a PR for the fix?

**Comment by xieshenzh** [comment]
> Thanks, @xiezhang7 , can you open a PR for the fix?

Sure
