### ISSUE TITLE
Upgrade controller-runtime to v0.7.0

### ISSUE THREAD

**Issue by LCaparelli** [RHsyseng/operator-utils#78]
The operator-sdk v1.3.0 uses `sigs.k8s.io/controller-runtime v0.7.0`. Upon attempting to migrate a project that uses operator-utils to this new version of the SDK we run into issues.

We're pulling `github.com/RHsyseng/operator-utils v1.4.6-0.20201105212318-34fe934c3a6b` (the latest commit at the main branch at the time of writing) and when attempting to sync dependencies we run into:

```
github.com/m88i/nexus-operator/controllers/nexus/resource imports
  github.com/RHsyseng/operator-utils/pkg/resource/compare imports
  sigs.k8s.io/controller-runtime/pkg/runtime/log: module sigs.k8s.io/controller-runtime@latest found (v0.7.0), but does not contain package sigs.k8s.io/controller-runtime/pkg/runtime/log
```

It would seem the culprit importer is `pkg/resource/compare/map.go`:

https://github.com/RHsyseng/operator-utils/blob/34fe934c3a6b53dd87cb8420e81f9b44bd0a99fd/pkg/resource/compare/map.go#L1-L7

In controller-runtime v0.7.0 the `pkg/runtime/log` [does not exist](https://github.com/kubernetes-sigs/controller-runtime/tree/master/pkg/runtime).

Noteworthy is that the `pkg/log/zap` package exists in both v0.6.3 and v0.7.0, and as far as I can tell it could be used as a substitute without much trouble. However, I am not sure that this is the only incompatibility with v0.7.0, so even if this is fixed by replacing the logger there could still be other problems.

**Comment by tchughesiv** [comment]
https://github.com/RHsyseng/operator-utils/pull/83
